# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ROS Controller' do
  # Pods for ROS Controller
  pod 'BRHJoyStickView', '~> 3.2'
  pod 'SwiftSocket'  

end
